# Generated by Django 3.2.25 on 2024-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(null=True),
        ),
    ]
