# Generated by Django 5.0.6 on 2024-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
