# Generated by Django 5.0.6 on 2024-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
