# Generated by Django 5.0.6 on 2024-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_movie_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(),
        ),
    ]
