# Generated by Django 5.0.6 on 2024-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_tmdb_id_alter_movie_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='content',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='vote_average',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='update_date',
        ),
        migrations.AddField(
            model_name='category',
            name='genre_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='blog.category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
