# Generated by Django 5.0.6 on 2024-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_movie_options_rename_content_movie_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
