# Generated by Django 5.0.6 on 2024-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
