# Generated by Django 5.0.6 on 2024-09-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_rating_unique_together_rating_rated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie_id_explicit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
